[package]
name = "upcast-arithmetic"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "Arithmetic that is upcasted on overflow"
repositiory = "https://github.com/umgefahren/upcast-arithmetic"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
